/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.pruebaexcepcionespag400;

import javax.swing.JOptionPane;

/**
 *
 * @author danil
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName());

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Numerador = new javax.swing.JLabel();
        Denominador = new javax.swing.JLabel();
        CNumerador = new javax.swing.JTextField();
        CDenominador = new javax.swing.JTextField();
        Cociente = new javax.swing.JLabel();
        CCociente = new javax.swing.JTextField();
        btnCalcular = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Numerador.setText("Numerador");

        Denominador.setText("Denominador");

        CNumerador.addActionListener(this::CNumeradorActionPerformed);

        CDenominador.addActionListener(this::CDenominadorActionPerformed);

        Cociente.setText("Cociente");

        CCociente.addActionListener(this::CCocienteActionPerformed);

        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(this::btnCalcularActionPerformed);

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(this::btnLimpiarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Numerador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Denominador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Cociente, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CNumerador, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CDenominador, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CCociente, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(btnCalcular)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLimpiar)))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Numerador)
                    .addComponent(CNumerador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Denominador)
                    .addComponent(CDenominador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CCociente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cociente))
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCalcular)
                    .addComponent(btnLimpiar))
                .addContainerGap(82, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CNumeradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CNumeradorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CNumeradorActionPerformed

    private void CDenominadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CDenominadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CDenominadorActionPerformed

    private void CCocienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CCocienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CCocienteActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed

    try {
        JOptionPane.showMessageDialog(null,"Ingresando al primer try","Atencion",JOptionPane.ERROR_MESSAGE);
        double numerador = Double.parseDouble(CNumerador.getText());
        double denominador = Double.parseDouble(CDenominador.getText());
        double cociente = numerador/denominador;
        CCociente.setText(String.valueOf(cociente));
        System.out.println("Después de la división");
        JOptionPane.showMessageDialog(null,"Ingresando al primer try","Atencion",JOptionPane.INFORMATION_MESSAGE);
        }   

    catch (ArithmeticException e) {
    JOptionPane.showMessageDialog(null,"División por cero","Atencion",JOptionPane.INFORMATION_MESSAGE);
} 
    finally {
        JOptionPane.showMessageDialog(null,"Ingresando al primer finally","Atencion",JOptionPane.INFORMATION_MESSAGE);
}
// Segundo bloque try
try {
    JOptionPane.showMessageDialog(null,"Ingresando al segundo try","Atencion",JOptionPane.INFORMATION_MESSAGE);
Object objeto = null;
objeto.toString();
JOptionPane.showMessageDialog(null,"Imprimiendo objeto","Atencion",JOptionPane.INFORMATION_MESSAGE);
}
catch (ArithmeticException e) {
    JOptionPane.showMessageDialog(null,"División por cero","Atencion",JOptionPane.INFORMATION_MESSAGE);
}
catch (Exception e) {
    JOptionPane.showMessageDialog(null,"Ocurrió una excepción","Atencion",JOptionPane.INFORMATION_MESSAGE);
}

finally {
    JOptionPane.showMessageDialog(null,"Ingresando al segundo finally","Atencion",JOptionPane.INFORMATION_MESSAGE);

    
    

}    }//GEN-LAST:event_btnCalcularActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        CNumerador.setText("");
        CDenominador.setText("");
        CCociente.setText("");
    }//GEN-LAST:event_btnLimpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CCociente;
    private javax.swing.JTextField CDenominador;
    private javax.swing.JTextField CNumerador;
    private javax.swing.JLabel Cociente;
    private javax.swing.JLabel Denominador;
    private javax.swing.JLabel Numerador;
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnLimpiar;
    // End of variables declaration//GEN-END:variables
}
